# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode
resources:
  repositories:
  - repository: tox
    type: github
    endpoint: toxdevorg
    name: tox-dev/azure-pipelines-template
    ref: refs/tags/0.2

jobs:
  - template: ./ci-jobs/functional_test.yml

  - template: run-tox-env.yml@tox
    parameters:
      tox_version: ""
      jobs:
        fix_lint: null
        docs: null
        py37:
          image: [linux]
        py38:
          image: [linux]
        py39:
          image: [linux]


# Runs tests nightly to make sure they works against appium@beta
schedules:
  - cron: "0 0 * * *"
    displayName: Daily Nightly build (UTC)
    branches:
      include:
        - master
    always: true
